<?php

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("INSERT INTO menu_item VALUES 
            ('access',NULL,0,'br','main',0,85,'ACCESS','index.php?mode=access','Controle de acesso: usuários, grupos, transações, programas, etc.','Acesso','fa fa-user',NULL,NULL,1,0),
            ('ACC_ADDER','access',1,'br','access',0,50,'ACC_ADDER','access_adder','Tabela de acumuladores','Acumuladores',NULL,NULL,'access',0,0),
            ('ACC_CONTR1','access',1,'br','access',0,200,'ACC_CONTRO','access_control','Controle de acesso por tipo de entidade, grupo e tipo de acesso','Manutenção de Acesso',NULL,NULL,'access',0,0),
            ('ACC_CONTRO','access',1,'br','access',0,100,'ACC_CONTRO','access_control','Manutenção direta da tabela de controles de acesso','Controle de Acesso',NULL,NULL,'access',0,0),
            ('ACC_ENTITY','access',1,'br','access',0,40,'ACC_ENTITY','access_entity','manutenção da tabela de entidades','Entidades',NULL,NULL,'access',0,0),
            ('ACC_ENTTYP','access',1,'br','access',0,30,'ACC_ENTTYP','access_entity_type','manutenção da tabela de tipos de entidade','Tipos de Entidade',NULL,NULL,'access',0,0),
            ('ACC_EVENT','access',1,'br','access',0,3000,'ACC_EVENT','access_event','Manutenção de eventos','Eventos',NULL,NULL,'access',0,0),
            ('ACC_GROUPS','access',1,'br','access',0,20,'ACC_GROUPS','access_groups','Manutenção da tabela de grupos','Grupos',NULL,NULL,'access',0,0),
            ('ACC_MESSAG','access',1,'br','access',0,250,'ACC_MESSAG','access_message','Manutenção da tabela de mensagens','Mensagem',NULL,NULL,'access',0,0),
            ('ACC_PASSEX',NULL,1,'br','access',0,20,'ACC_PASSEX','access_password_expiration','Expiração de Senhas','Expiração de Senhas',NULL,NULL,'access',0,0),
            ('ACC_PASSPO',NULL,1,'br','access',0,12,'ACC_PASSPO','access_password_policy','Política de Segurança','Política de Segurança',NULL,NULL,'access',0,0),
            ('ACC_PASSWD','access',1,'br','access',0,70,'ACC_PASSWD','access_passwd','Alterar Senha','Alterar Senha',NULL,NULL,'access',0,0),
            ('ACC_TYPE','access',1,'br','access',0,60,'ACC_TYPE','access_type','Manutenção da tabela de tipos de acesso','Tipos de Acesso',NULL,NULL,'access',0,0),
            ('ACC_TYPEOP','access',1,'br','access',0,45,'ACC_TYPEOP','access_type_operation','Tipos de Operação','Tipos de Operação',NULL,NULL,'access',0,0),
            ('ACC_USERS','access',1,'br','access',0,10,'ACC_USERS','access_users','Manutenção da tabela de usuários','Usuários',NULL,NULL,'access',0,0),
            ('amount',NULL,0,'br','main',0,6,'AMOUNT','index.php?mode=amount','Acompanhamento de Vendas: por finalizadora, por item, etc.','Vendas','glyphicon glyphicon-shopping-cart',NULL,NULL,1,0),
            ('AMO_ACCUM','MAMO_ITEM',2,'br','amount',0,920,'AMO_ACCUM','amount_accum','Vendas por Item - Periodo','Itens por periodo',NULL,NULL,'amount',0,0),
            ('AMO_AVRGPR','MAMO_ESTAT',2,'br','amount',0,300,'AMO_AVRGPR','amount_process_average','Média de Processamento','Média de Processamento',NULL,NULL,'amount',0,0),
            ('AMO_BAG','amount',1,'br','amount',0,356,'AMO_BAG','amount_bag_report','Relatório de sacolas','Relatório de sacolas',NULL,NULL,'amount',0,0),
            ('AMO_BANKIN','MAMO_MEDIA',2,'br','amount',0,570,'AMO_BANKIN','amount_banking','Sangria / Fundo de Troco','Sangria / Fundo de Troco',NULL,NULL,'amount',0,0),
            ('AMO_BASE','MAMO_ITEM',2,'br','amount',0,930,'AMO_BASE','amount_base','Vendas por Periodo de Grupos de Itens','Grupos de Itens',NULL,NULL,'amount',0,0),
            ('AMO_BIRTH','MAMO_ESTAT',2,'br','amount',0,500,'AMO_BIRTH','assai_birthday','Campanha Assai - vale Brinde 100','Campanha Assai - vale Brinde 100',NULL,NULL,'amount',0,1),
            ('AMO_CBACK','MAMO_OTHER',2,'br','amount',0,100,'AMO_CBACK','amount_cash_back','Visualização de Saques','Saques',NULL,NULL,'AMOUNT',0,0),
            ('AMO_CELOPE','MAMO_OTHER',2,'br','amount',0,12,'AMO_CELOPE','amount_operator','Consulta de Vendas por Operadora de Celular','Vendas por Operadora de Celular',NULL,NULL,'amount',0,0),
            ('AMO_CHECK','MAMO_TOTAL',2,'br','amount',0,1120,'AMO_CHECK','amount_check','Checagem de Vendas por Item','Checagem',NULL,NULL,'amount',0,0),
            ('AMO_CHECKL','MAMO_MEDIA',2,'br','amount',0,560,'AMO_CHECKL','amount_checklist','Lista de Cheques','Lista de Cheques',NULL,NULL,'amount',0,0),
            ('AMO_CLERK','MAMO_OPER',2,'br','amount',0,630,'AMO_CLERK','amount_clerk','Vendas por Vendedor','Vendedor',NULL,NULL,'amount',0,0),
            ('AMO_COMM','MAMO_OPER',2,'br','amount',0,665,'AMO_COMM','amount_clerk_commission','Comissões por Vendedor','Comissões',NULL,NULL,'amount',0,0),
            ('AMO_CORBAN','MAMO_OTHER',2,'br','amount',0,50,'AMO_CORBAN','amount_cor_bank','Correspondente Bancario','Correspondente Bancario',NULL,NULL,'amount',0,0),
            ('AMO_DEPOS','MAMO_RTN',2,'br','amount',0,850,'AMO_DEPOS','amount_deposit','Consulta de troca de vasilhame','Vasilhame',NULL,NULL,'amount',0,0),
            ('AMO_DEPOSITM','MAMO_RTN',2,'br','amount',0,950,'AMO_DEPOS','amount_deposit','Status das trocas de vasilhame por item','Vasilhame/Item',NULL,NULL,'amount',0,0),
            ('AMO_DEPTS','MAMO_DEP',2,'br','amount',0,810,'AMO_DEPTS','amount_depts','Vendas por Departamento','Departamento',NULL,NULL,'amount',0,0),
            ('AMO_DISAUT','MAMO_DSC',2,'br','amount',0,50,'AMO_DISAUT','amount_discount_authorizer','Descontos por autorizador','Descontos por autorizador',NULL,NULL,'amount',0,0),
            ('AMO_DISCNT','MAMO_DSC',2,'br','amount',0,25,'AMO_DISCNT','amount_discount','Descontos','Descontos',NULL,NULL,'amount',0,0),
            ('AMO_DISCNT1','MAMO_DSC',2,'br','amount',0,12,'AMO_DISCNT','amount_discount_reason','Descontos por Motivo','Descontos 1',NULL,NULL,'amount',0,0),
            ('AMO_DPTR','MAMO_DEP',2,'br','amount',0,820,'AMO_DPTR','amount_depts','Vendas por Departamento','Departamentos Estruturados',NULL,NULL,'amount',0,0),
            ('AMO_DPTRHR','MAMO_DEP',2,'br','amount',0,830,'AMO_DPTRHR','amount_depts','Vendas por Departamento / Faixa Horária','Departamentos / Faixa Horária',NULL,NULL,'amount',0,0),
            ('AMO_DSCREA',NULL,1,'br','amount',0,9600,'AMO_DSCREA','amount_discount_reason','Motivos de  Desconto','Motivos de  Desconto',NULL,NULL,'amount',0,0),
            ('AMO_FISCAL','MAMO_FISC',2,'br','amount',0,1010,'AMO_FISCAL','amount_fiscal','Totais Fiscais','Reduções Z',NULL,NULL,'amount',0,0),
            ('AMO_ITEM','MAMO_ITEM',2,'br','amount',0,910,'AMO_ITEM','amount_item','Vendas por Item','Itens',NULL,NULL,'amount',0,0),
            ('AMO_ITMSRV','MAMO_TCKT',2,'br','amount',0,37,'AMO_ITMSRV','amount_ticket_service','Consulta items do tickets por tipo de serviço','Itens com Serviços',NULL,NULL,'amount',0,0),
            ('AMO_LOGIT','MAMO_ITEM',2,'br','amount',0,940,'AMO_LOGIT','amount_logitem','Extrato de Item','Extrato',NULL,NULL,'amount',0,0),
            ('AMO_MAKER','amount',1,'br','amount',0,210,'AMO_MAKER','amount_makers','Vendas por Fornecedor','Fornecedor',NULL,NULL,'amount',0,0),
            ('AMO_MEDIA','amount',1,'br','amount',0,11,'AMO_MEDIA','amount_media','Totais por Finalizadora','Finalizadoras',NULL,NULL,'amount',0,0),
            ('AMO_MEDIAC','amount',1,'br','amount',0,270,'AMO_MEDIAC','amount_mediaper','Comparativo de Vendas por Periodo','Comparativo por Periodo',NULL,NULL,'amount',0,0),
            ('AMO_MEDIAM','x_amount',1,'br','x_amount',0,310,'AMO_MEDIAM','amount_mediamcc','Finalizações MCC','Finalizações MCC',NULL,NULL,'x_amount',0,0),
            ('AMO_MEDIAP','MAMO_MEDIA',2,'br','amount',0,550,'AMO_MEDIAP','amount_mediatot','Vendas por Periodo','Vendas por Periodo',NULL,NULL,'amount',0,0),
            ('AMO_MEDIAT','MAMO_MEDIA',2,'br','amount',0,540,'AMO_MEDIAT','amount_mediatkt','Finalizações','Finalizações',NULL,NULL,'amount',0,0),
            ('AMO_MEF','MAMO_FISC',2,'br','amount',0,1120,'AMO_MEF','amount_mef','Consulta Leitura MEF','Leitura MEF',NULL,NULL,'amount',0,0),
            ('AMO_METRCOP','MAMO_OPER',2,'br','amount',0,686,'AMO_METRCO','amount_metric_oper','Metrica de Operador','Metrica de Operador',NULL,NULL,'amount',0,0),
            ('AMO_METRIC','MAMO_OPER',2,'br','amount',0,682,'AMO_METRIC','amount_metric','Metrica Por Operador','Metrica',NULL,NULL,'amount',0,0),
            ('AMO_NFCE','MAMO_TCKT',2,'br','amount',0,50,'AMO_NFCE','amount_check_nfce','Vendas NFCe','Vendas NFCe',NULL,NULL,'amount',0,0),
            ('AMO_NOCRETURN','MAMO_RTN',2,'br','amount',0,715,'AMO_NRCON','amount_return_control','Trocas de Mercadorias (sem cupom)','Troca/Reembolso (sem cupom)',NULL,NULL,'amount',0,1),
            ('AMO_NRCON','MAMO_RTN',2,'br','amount',0,712,'AMO_NRCON','amount_return_control','Trocas de Mercadorias (sem cupom)','Troca/Reembolso (sem cupom)',NULL,NULL,'amount',0,1),
            ('AMO_OBLATA','amount',1,'br','amount',0,24,'AMO_OBLATA','amount_oblata','Consulta de Vendas por Campanha','Vendas por Campanha',NULL,NULL,'amount',0,0),
            ('AMO_OBLREP',NULL,1,'br','amount',0,30,'AMO_OBLREP','amount_oblata_result','Resultado de Campanha','Resultado de Campanha',NULL,NULL,'amount',0,0),
            ('AMO_OBLRES','MAMO_TCKT',2,'br','amount',0,300,'AMO_OBLRES','amount_oblata_result','Resultado de  Campanha','Resultado de Campanha',NULL,NULL,'amount',0,0),
            ('AMO_OBLTKT','MAMO_OTHER',2,'br','amount',0,1,'AMO_OBLTKT','amount_oblata_ticket','Cupons Sorteio','Cupons Sorteio',NULL,NULL,'amount',0,0),
            ('AMO_OBLTOT','MAMO_TCKT',2,'br','amount',0,200,'AMO_OBLTOT','amount_oblata_tot','Consulta do Total de Vendas por Campanha','Total de Vendas por Campanha',NULL,NULL,'amount',0,0),
            ('AMO_OPER','MAMO_OPER',2,'br','amount',0,610,'AMO_OPER','amount_oper','Totais por Operador','Operadores',NULL,NULL,'amount',0,0),
            ('AMO_PARTRF','MAMO_RTN',2,'br','amount',0,730,'AMO_PARTRF','amount_part_refund','Reembolso de Diferenças','Reembolsos',NULL,NULL,'amount',0,0),
            ('AMO_PAYMEN','MAMO_OTHER',2,'br','amount',0,25,'AMO_PAYMEN','amount_payment','Pagamentos','Pagamentos',NULL,NULL,'amount',0,0),
            ('AMO_PBMREL','amount',1,'br','amount',0,28,'AMO_PBMREL','amount_ticket_pbm','Consulta de tickets de PBMs','Vendas PBMs',NULL,NULL,'amount',0,0),
            ('AMO_PLAN','amount',1,'br','amount',0,327,'AMO_PLAN','amount_plan','Vendas Parceladas','Vendas Parceladas',NULL,NULL,'amount',0,0),
            ('AMO_POLL',NULL,1,'br','amount',0,27,'AMO_POLL','amount_poll','Resultado Pesquisa de Cliente','Pesquisa Cliente',NULL,NULL,'amount',0,0),
            ('AMO_POS','MAMO_ITEM',2,'br','amount',0,950,'AMO_POS','amount_pos','Vendas por PDV','PDV',NULL,NULL,'amount',0,0),
            ('AMO_PRICE','amount',1,'br','amount',0,160,'AMO_PRICE','amount_price','Vendas por Tipo de Preço','Tipo de Preço',NULL,NULL,'amount',0,0),
            ('AMO_PROD','MAMO_OPER',2,'br','amount',0,700,'AMO_PROD','amount_oper_prod','Relatorio de Produtividade','Relatorio de Produtividade',NULL,NULL,NULL,NULL,NULL),
            ('AMO_PROMOT','MAMO_TCKT',2,'br','amount',0,250,'AMO_PROMOT','amount_promotion','Vendas por Campanha','Vendas por Campanha',NULL,NULL,'amount',0,0),
            ('AMO_QUERY','MAMO_OTHER',2,'br','amount',0,2,'AMO_QUERY','amount_query','Controle de consulta no PDV','Controle de consulta',NULL,NULL,'amount',0,0),
            ('AMO_RANK','MAMO_OTHER',2,'br','amount',0,150,'AMO_RANK','amount_ranking','Ranking de Cupons','Ranking',NULL,NULL,'amount',0,0),
            ('AMO_REFUND','MAMO_RTN',2,'br','amount',0,720,'AMO_REFUND','amount_refund','Devoluções de Mercadorias','Devoluções',NULL,NULL,'amount',0,0),
            ('AMO_RETURN','MAMO_RTN',2,'br','amount',0,710,'AMO_RETURN','amount_return','Trocas de Mercadorias','Trocas',NULL,NULL,'amount',0,0),
            ('AMO_RFITEM','MAMO_RTN',2,'br','amount',0,750,'AMO_RFITEM','amount_refunded_item','Consulta de Itens com Reembolso Parcial','Reembolsos por Item',NULL,NULL,'amount',0,0),
            ('AMO_RITEM','MAMO_RTN',2,'br','amount',0,740,'AMO_RITEM','amount_returned_item','Consulta de Itens Devolvidos','Itens Devolvidos',NULL,NULL,'amount',0,0),
            ('AMO_RTBOTTLE','MAMO_RTN',2,'br','amount',0,1050,'AMO_RTBOTT','amount_return_bottle','Lançamento de Devolução de vasilhames','Lançamento de Devolução de vasilhames',NULL,NULL,'amount',0,0),
            ('AMO_RVSKIT','NULL',1,'br','amount',0,2300,'AMO_RVSKIT','amount_reverse_kit','Vendas de kit reverso','Vendas de kit reverso',NULL,NULL,'amount',0,0),
            ('AMO_SALEPH','MAMO_ESTAT',2,'br','amount',0,200,'AMO_SALEPH','amount_sale_per_hour','Vendas Por Faixa Horária','Vendas Por Faixa Horária',NULL,NULL,'amount',0,0),
            ('AMO_SAT','MAMO_TOTAL',2,'br','amount',0,1220,'AMO_SAT','amount_check_sat','Checagem de Vendas por SAT','Checagem SAT',NULL,NULL,'amount',0,0),
            ('AMO_SEAL','MAMO_OTHER',2,'br','amount',0,250,'AMO_SEAL','amount_seal','Selos','Selos',NULL,NULL,'amount',0,0),
            ('AMO_SERV','MAMO_OTHER',2,'br','amount',0,6,'AMO_SERV','amount_service','Manutencao de convenio de estacionamento','Convenio Estacionamento',NULL,NULL,'amount',0,0),
            ('AMO_STAT','MAMO_ESTAT',2,'br','amount',0,50,'AMO_STAT','amount_stat','Estatística de Venda','Estatística',NULL,NULL,'amount',0,0),
            ('AMO_STIME','MAMO_OPER',2,'br','amount',0,691,'AMO_STIME','amount_exit_time','Saida Temporária','Saida Temporária',NULL,NULL,'amount',0,0),
            ('AMO_STOP','MAMO_OPER',2,'br','amount',0,620,'AMO_STOP','amount_statope','Produtividade por Operador','Produtividade',NULL,NULL,'amount',0,0),
            ('AMO_STSALE','MAMO_ESTAT',2,'br','amount',0,100,'AMO_STSALE','amount_statistic_sale','Estatísticas de Vendas','Estatísticas de Vendas',NULL,NULL,'amount',0,0),
            ('AMO_TEF','MAMO_MEDIA',2,'br','amount',0,530,'AMO_TEF','amount_tef','Resumo de Cartoes','Resumo Cartoes',NULL,NULL,'amount',0,0),
            ('AMO_TICKET','amount',1,'br','amount',0,22,'AMO_TICKET','amount_ticket','Vendas por Ticket','Tickets',NULL,NULL,'amount',0,0),
            ('AMO_TKTCST','MAMO_TCKT',2,'br','amount',0,100,'AMO_TKTCST','amount_ticket_custom','Seleção de transações por tipo','Transações por Tipo',NULL,NULL,'amount',0,0),
            ('AMO_TKTNFP','amount',1,'br','amount',0,25,'AMO_TKTNFP','amount_ticket_nfp','Vendas por Ticket NFP','Tickets NFP',NULL,NULL,'amount',0,0),
            ('AMO_TKTSRV','MAMO_TCKT',2,'br','amount',0,25,'AMO_TKTSRV','amount_ticket_service','Consulta tickets por serviço','Tickets por serviço',NULL,NULL,'amount',0,0),
            ('AMO_TOTAL','MAMO_TOTAL',2,'br','amount',0,1110,'AMO_TOTAL','amount_total','Comparativo de Vendas Liquidas','Comparativo',NULL,NULL,'amount',0,0),
            ('AMO_TOTITM','MAMO_TCKT',2,'br','amount',0,400,'AMO_TOTITM','amount_ticket_tot_itm','Consulta total de cupons vendidos na campanha','Cupons vendidos na campanha',NULL,NULL,'amount',0,0),
            ('AMO_TOTPOS','MAMO_ESTAT',2,'br','amount',0,400,'AMO_TOTPOS','amount_total_pos','Atividades por PDV','Atividades por PDVs',NULL,NULL,'amount',0,0),
            ('AMO_TOTSTO','amount',1,'br','amount',0,26,'AMO_TOTSTO','amount_store','Totais de Venda por Loja','Vendas por Loja',NULL,NULL,'amount',0,0),
            ('AMO_TRFNL','MAMO_TOTAL',2,'br','amount',0,1320,'AMO_TRFNL','amount_media_swap','Troca de Finalizadora','Troca de Finalizadora',NULL,NULL,'amount',0,0),
            ('AMO_TRIBUT','MAMO_FISC',2,'br','amount',0,1020,'AMO_TRIBUT','amount_tributo','Totais de Impostos por período','Impostos',NULL,NULL,'amount',0,0),
            ('AMO_TTRPT','amount',1,'br','amount',0,30,'AMO_TTRPT','amount_total_report','Relatório de Totais','Relatório de Totais',NULL,NULL,'amount',0,0),
            ('AMO_TTSTAN',NULL,1,'br','amount',0,26,'AMO_TTSTAN','amount_store_analytical','Totais de Venda por Loja - Analítico','Vendas por Loja Analítico',NULL,NULL,'amount',0,0),
            ('AMO_TYPPRC',NULL,1,'br','amount',0,3200,'AMO_TYPPRC','amount_type_price','Clientes por Tipo de Preço','Clientes por Tipo de Preço',NULL,NULL,NULL,0,0),
            ('AMO_VDTEF','MAMO_OTHER',2,'br','amount',0,3,'AMO_VDTEF','amount_voidedtef','Estornos de transações de Transferência Eletrônica de Fundos','Cancelamentos TEF',NULL,NULL,'amount',0,0),
            ('AMO_VOIDED','amount',1,'br','amount',0,130,'AMO_VOIDED','amount_voided','Cancelamentos de Vendas, Cupons e Itens de venda','Cancelamentos',NULL,NULL,'amount',0,0),
            ('AMO_VOIREA','amount',1,'br','amount',0,145,'AMO_VOIREA','amount_void_reason','Cancelamentos por Motivo','Cancelamentos por Motivo',NULL,NULL,'amount',0,0),
            ('AMT_LBLPRM','MAMO_TCKT',2,'br','amount',0,500,'AMT_LBLPRM','amount_label_promotion','Campanha relampago','Vendas de Campanha relampago',NULL,NULL,'amount',0,0),
            ('CERT_NFCE','store',1,'br','store',0,335,'CERT_NFCE','store_certificados_nfce','Certificados','Certificados',NULL,NULL,'store',0,0),
            ('CNSD_GCG','treasury',1,'br','treasury',0,1152,'CNSD_GCG','cnsd_guide_blind','Lançamento de guia cega','Lançamento de guia cega',NULL,NULL,'treasury',0,0),
            ('copyright','x_main',0,'br','x_main',0,16,'COPYRIGHT','copy.html','Sobre','Dados do Sistema',NULL,NULL,NULL,1,0),
            ('CST_ADDRTP','customer',1,'br','customer',0,40,'CST_ADDRTP','customer_addr_type','manutenção da tabela de tipos de endereços','Tipos de Endereço',NULL,NULL,'customer',0,0),
            ('CST_CSTPT','customer',1,'br','customer',0,160,'CST_CSTPT','customer_points','Manutenção dos pontos de campanha','Pontos de Campanha',NULL,NULL,'customer',0,0),
            ('CST_DLDPAY','customer',1,'br','customer',0,1700,'CST_DLDPAY','customer_delayed_pay','Registro de dias de adiamentos','Registro de dias de adiamentos',NULL,NULL,'customer',0,1),
            ('CST_DOTZ','customer',1,'br','customer',0,1400,'CST_DOTZ','customer_cupom_dotz','Cupons dotz','Cupom dotz',NULL,NULL,NULL,0,0),
            ('CST_EXTPTS','customer',1,'br','customer',0,1800,'CST_EXTPTS','customer_external_points','Controle de Pontos','Controle de Pontos',NULL,NULL,'customer',0,1),
            ('CST_FILE','customer',1,'br','customer',0,10,'CST_FILE','customer_file','Manutenção da tabela de clientes','Clientes',NULL,NULL,'customer',0,0),
            ('CST_FILE_FT','customer',1,'br','customer',0,15,'CST_FILE_F','customer_file','Cadastro de cliente Rapido','Clientes Rapido',NULL,NULL,'customer',0,0),
            ('CST_FISCTP','customer',1,'br','customer',0,130,'CST_FISCTP','customer_fisc_type','Manutenção da tabela de categorias fiscais de clientes','Categoria Fiscal',NULL,NULL,'customer',0,0),
            ('CST_LEFT','customer',1,'br','customer',0,150,'CST_LEFT','customer_left','Baixa de saldo de clientes','Baixa de Saldo',NULL,NULL,'customer',0,0),
            ('CST_MEDIA','customer',1,'br','customer',0,140,'CST_MEDIA','customer_media','Vendas por tipo de cliente','Vendas',NULL,NULL,'customer',0,0),
            ('CST_POLL','customer',1,'br','customer',0,1600,'CST_POLL','customer_poll','Manutenção de Enquetes','Enquetes',NULL,NULL,'customer',0,1),
            ('CST_POLLV','customer',1,'br','customer',0,1500,'CST_POLLV','customer_poll_result','Resultados de enquetes','Resultados de enquetes',NULL,NULL,'customer',0,1),
            ('CST_RESTRC','customer',1,'br','customer',0,20,'CST_RESTRC','customer_restriction','Manutenção da tabela de tipos de restrições','Restrições',NULL,NULL,'customer',0,0),
            ('CST_SKUTYP','customer',1,'br','customer',0,110,'CST_SKUTYP','customer_sku_type','Manutenção da tabela de tipos de identificação','Tipos de Identificação',NULL,NULL,'customer',0,0),
            ('CST_SRSTP','customer',1,'br','customer',0,105,'CST_SRSTP','customer_serasa_type','Manutenção da tabela de Status do SERASA','SERASA',NULL,NULL,'customer',0,0),
            ('CST_STSTP','customer',1,'br','customer',0,100,'CST_STSTP','customer_sts_type','Manutenção da tabela de situações (Status) de clientes','Status',NULL,NULL,'customer',0,0),
            ('CST_TRANS','customer',1,'br','customer',0,780,'CST_TRANS','customer_transaction','Transações de Clientes','Transações',NULL,NULL,'customer',0,0),
            ('CST_TYPE','customer',1,'br','customer',0,30,'CST_TYPE','customer_type','Manutenção da tabela de tipos de clientes','Tipos de Cliente',NULL,NULL,'customer',0,0),
            ('customer',NULL,0,'br','main',0,83,'CUSTOMER','index.php?mode=customer','Controle de clientes: dados cadastrais, saldo, situação, compras, etc.','Clientes','fa fa-users',NULL,NULL,1,0),
            ('CUS_CONF','MPART_CUS',2,'br','partner',0,200,'CUS_CONF','custodiam_conf','Configuração de Transmissão DBOnline','Configuração',NULL,NULL,'partner',0,0),
            ('CUS_TKT','MPART_CUS',2,'br','partner',0,100,'CUS_TKT','custodiam_ticket','Relatorio de Transmissão DBOnline','Transmissão',NULL,NULL,'partner',0,0),
            ('CUS_USER','MPART_CUS',2,'br','partner',0,300,'CUS_USER','custodiam_user','Usuários de transmissão DBOnline','Usuários',NULL,NULL,'partner',0,0),
            ('DASH_COR','dashboard',1,'br','dashboard',0,600,'DASH_COR','dashboard/index','Dashboard Configuração Cor','Dashboard Configuração Cor',NULL,NULL,'dashboard',0,0),
            ('DASH_NFCE','dashboard',1,'br','dashboard',0,400,'DASH_NFCE','dashboard/index','Dashboard Vendas por NFCE','Dashboard Vendas por NFCE',NULL,NULL,'dashboard',0,0),
            ('DASH_SALE','dashboard',1,'br','dashboard',0,100,'DASH_SALE','dashboard/index','Dashboard Vendas por loja','Dashboard Vendas por loja',NULL,NULL,'dashboard',0,0),
            ('DASH_SALEAG','dashboard',1,'br','dashboard',0,200,'DASH_SALEA','dashboard/index','Dashboard Vendas por Vendedor','Dashboard Vendas por Vendedor',NULL,NULL,'dashboard',0,0),
            ('DASH_SALETP','dashboard',1,'br','dashboard',0,300,'DASH_SALET','dashboard/index','Dashboard Vendas por Tipo','Dashboard Vendas por Tipo',NULL,NULL,'dashboard',0,0),
            ('DASH_SAT','dashboard',1,'br','dashboard',0,500,'DASH_SAT','dashboard/index','Dashboard Vendas por SAT','Dashboard Vendas por SAT',NULL,NULL,'dashboard',0,0),
            ('gas',NULL,0,'br','main',0,54,'GAS','index.php?mode=gas_station','Posto de Combustivel','Posto',NULL,NULL,NULL,1,1),
            ('GAS_ACCTK','gas_station',1,'br','gas_station',0,1492,'GAS_ACCTK','gas_station_accum_tank','Acumulado por Tanque','Acumulado por Tanque',NULL,NULL,'gas_station',0,0),
            ('GAS_AMOSTO','gas_station',1,'br','gas_station',0,977,'GAS_AMOSTO','gas_station_amount_stock','Vendas/Estoque','Vendas/Estoque',NULL,NULL,'gas_station',0,0),
            ('GAS_BANKIN','gas_station',1,'br','gas_station',0,1599,'GAS_BANKIN','gas_station_banking','Sangria por Frentista','Sangria Frentista',NULL,NULL,'gas_station',0,0),
            ('GAS_BNKUSR','gas_station',1,'br','gas_station',0,1474,'GAS_BNKUSR','gas_station_banking_user','Relatório de Sangrias por Usuário','Relatório de Sangrias por Usuário',NULL,NULL,'gas_station',0,0),
            ('GAS_CLBRT','gas_station',1,'br','gas_station',0,965,'GAS_CLBRT','gas_station_calibrating','Aferição de Bico','Aferição de Bico',NULL,NULL,'gas_station',0,0),
            ('GAS_CLOCHK','gas_station',1,'br','gas_station',0,969,'GAS_CLOCHK','gas_station_closing_check','Checagem de Encerrantes','Checagem de Encerrantes',NULL,NULL,'gas_station',0,0),
            ('GAS_CLOS','gas_station',1,'br','gas_station',0,966,'GAS_CLOS','gas_station_closing','Fechameto por data','Fechameto por data',NULL,NULL,'gas_station',0,0),
            ('GAS_COMMIS','gas_station',1,'br','gas_station',0,2787,'GAS_COMMIS','gas_station_commission','Comissões por Frentista','Comissões por Frentista',NULL,NULL,'gas_station',0,0),
            ('GAS_COV','gas_station',1,'br','gas_station',0,951,'GAS_COV','gas_station_lmc_cover','Termo de Abertura/Encerramento','Termo de Abertura/Encerramento',NULL,NULL,'gas_station',0,0),
            ('GAS_HISPV',NULL,1,'br','gas_station',0,980,'GAS_HISPV','gas_station_history_vol_price','Historico de Preço e Volume','Historico de Preço e Volume',NULL,NULL,NULL,NULL,NULL),
            ('GAS_HISVE','gas',1,'br','gas_station',0,1900,'GAS_HISVE','gas_station_stock_history','Histórico de Estoque e Vendas','Histórico de Estoque e Vendas',NULL,NULL,NULL,0,0),
            ('GAS_IDNUM','gas_station',1,'br','gas_station',0,1299,'GAS_IDNUM','gas_station_id_number','Cartões RFID','Cartões RFID',NULL,NULL,'gas_station',0,0),
            ('GAS_INTVTN','gas_station',1,'br','gas_station',0,995,'GAS_INTVTN','gas_station_intervention','Intervenções','Intervenções',NULL,NULL,'gas_station',0,0),
            ('GAS_INVPEN','gas_station',1,'br','gas_station',0,1486,'GAS_INVPEN','gas_station_outstanding','Notas Pendentes','Notas Pendentes',NULL,NULL,'gas_station',0,0),
            ('GAS_LITERS','gas_station',1,'br','gas_station',0,2800,'GAS_LITERS','gas_station_liters_received','Relatório de Litros de Combustíveis Recebidos','Litros de Combustíveis Recebidos',NULL,NULL,'gas_station',0,0),
            ('GAS_LMC','gas_station',1,'br','gas_station',0,949,'GAS_LMC','gas_station_lmc','LMC','LMC',NULL,NULL,'gas_station',0,0),
            ('GAS_MAICLO','gas_station',1,'br','gas_station',0,999,'GAS_MAICLO','gas_station_main_closing','Manutenção de Encerrantes','Manutenção de Encerrantes',NULL,NULL,'gas_station',0,0),
            ('GAS_NOZCHK','gas_station',1,'br','gas_station',0,989,'GAS_NOZCHK','gas_station_nozzle_check','Checagem de Abastecimento','Checagem de Abastecimento',NULL,NULL,'gas_station',0,0),
            ('GAS_NOZPRC','gas_station',1,'br','gas_station',0,2793,'GAS_NOZPRC','gas_station_price_nozzle','Checagem de bicos','Checagem de bicos',NULL,NULL,'gas_station',0,0),
            ('GAS_NOZZLE','gas_station',1,'br','gas_station',0,919,'GAS_NOZZLE','gas_station_nozzle','Bicos','Bicos',NULL,NULL,'gas_station',0,0),
            ('GAS_NUMLMC','gas_station',1,'br','gas_station',0,954,'GAS_NUMLMC','gas_station_num_lmc','Número LMC','Número LMC',NULL,NULL,'gas_station',0,0),
            ('GAS_PERCEN','gas_station',1,'br','gas_station',0,2750,'GAS_PERCEN','gas_station_percents','Percentuais de Ganhos e Perdas','Percentuais de Ganhos e Perdas',NULL,NULL,'gas_station',0,0),
            ('GAS_PERSOB','gas_station',1,'br','gas_station',0,2900,'GAS_PERSOB','gas_station_leavings','Relatório de Perdas e Sobras de Combustiveis','Perdas e Sobras de Combustiveis',NULL,NULL,'gas_station',0,0),
            ('GAS_PREAMO','gas_station',1,'br','gas_station',0,1199,'GAS_PREAMO','gas_station_prev_amount','Vendas Esperadas','Vendas Esperadas',NULL,NULL,'gas_station',0,0),
            ('GAS_PRICE','gas_station',1,'br','gas_station',0,1099,'GAS_PRICE','gas_station_pricing','Pesquisa x Preço','Pesquisa x Preço',NULL,NULL,'gas_station',0,0),
            ('GAS_PUMP','gas_station',1,'br','gas_station',0,929,'GAS_PUMP','gas_station_pump','Bombas','Bombas',NULL,NULL,'gas_station',0,0),
            ('GAS_RECNF','gas_station',1,'br','gas_station',0,961,'GAS_RECNF','gas_station_receiving','NF Combustivel','NF Combustivel',NULL,NULL,'gas_station',0,0),
            ('GAS_REFUEL','gas_station',1,'br','gas_station',0,1499,'GAS_REFUEL','gas_station_refueling','Abastecimentos','Abastecimentos',NULL,NULL,'gas_station',0,0),
            ('GAS_SLUSR','gas_station',1,'br','gas_station',0,1480,'GAS_SLUSR','gas_station_sale_user','Vendas por Frentista','Relatório de Vendas por Frentista',NULL,NULL,'gas_station',0,0),
            ('gas_station',NULL,0,'br','main',0,1080,'GAS','index.php?mode=gas_station','Posto de Combustivel','Posto','img/gas.png',NULL,NULL,1,1),
            ('GAS_STCON','gas_station',1,'br','gas_station',0,2700,'GAS_STCON','gas_station_stock_consolidated','Vendas/Estoque Consolidado','Vendas/Estoque Consolidado',NULL,NULL,'gas_station',0,0),
            ('GAS_STOACC','gas_station',1,'br','gas_station',0,974,'GAS_STOACC','gas_station_store_accum','Acumulado de Vendas','Acumulado de Vendas',NULL,NULL,'gas_station',0,0),
            ('GAS_STOCK','gas_station',1,'br','gas_station',0,959,'GAS_STOCK','gas_station_stock','Estoque','Estoque',NULL,NULL,'gas_station',0,0),
            ('GAS_SUPSRV','gas_station',1,'br','gas_station',0,2775,'GAS_SUPSRV','gas_station_super_service','Configuração do SuperService','Configuração do SuperService',NULL,NULL,'gas_station',0,0),
            ('GAS_TANK','gas_station',1,'br','gas_station',0,939,'GAS_TANK','gas_station_tank','Tanques','Tanques',NULL,NULL,'gas_station',0,0),
            ('GAS_TICKET','gas_station',1,'br','gas_station',0,963,'GAS_TICKET','gas_station_ticket','Consulta de Nota','Consulta de Nota',NULL,NULL,'gas_station',0,0),
            ('GAS_TKTMEA','gas_station',1,'br','gas_station',0,1449,'GAS_TKTMEA','gas_station_measure_ticket','Tickets de Aferição','Tickets de Aferição',NULL,NULL,'gas_station',0,0),
            ('GAS_USERID','gas_station',1,'br','gas_station',0,1399,'GAS_USERID','gas_station_user_id','Usuário RFID','Usuário RFID',NULL,NULL,'gas_station',0,0),
            ('gateway',NULL,0,'br','main',0,84,'GATEWAY','index.php?mode=gateway','Administração dos gateways do sistema e do servidor','Gateway','glyphicon glyphicon-globe',NULL,NULL,1,0),
            ('GFT_CLERK','gift_list',1,'br','gift_list',0,200,'GFT_CLERK','gift_list_amount_clerk','Vendas por vendedor','Totais de venda por vendedor',NULL,NULL,'gift_list',0,0),
            ('GFT_CLERKT','gift_list',1,'br','gift_list',0,300,'GFT_CLERKT','gift_list_amount_clerk_totals','Vendas por vendedor - Quantitativo x Qualitativo','Totais Vendedor Quantitativo/Qualitativo',NULL,NULL,'gift_list',0,0),
            ('GFT_EDTKT','gift_list',1,'br','gift_list',0,100,'GFT_EDTKT','gift_list_ticket','Edição de ticket','Edição de ticket',NULL,NULL,'gift_list',0,0),
            ('GFT_FILE',NULL,1,'br','gift_list',0,802,'GFT_FILE','gift_list_file','Lista de Presentes','Lista de Presentes',NULL,NULL,'gift_list',0,0),
            ('GFT_TYPE',NULL,1,'br','gift_list',0,801,'GFT_TYPE','gift_list_type','Tipo de Lista','Tipo de Lista',NULL,NULL,'gift_list',0,0),
            ('gift_list',NULL,0,'br','main',0,87,'GFT_LIST','index.php?mode=gift_list','Manutenção do Cadastro de Listas','Listas','img/gift_list.gif',NULL,NULL,1,1),
            ('GTW_PARAM','gateway',1,'br','gateway',0,20,'GTW_PARAM','gateway_param','Parâmetros dos gateways','Parâmetros',NULL,NULL,'gateway',0,0),
            ('GTW_STATUS','gateway',1,'br','gateway',0,10,'GTW_STATUS','gateway_status','Status dos gateways','Status',NULL,NULL,'gateway',0,0),
            ('help',NULL,0,'br','main',0,90,'HELP','javascript:help','Ajuda global, para este módulo ou para esta tela','Ajuda','glyphicon glyphicon-question-sign',NULL,NULL,3,0),
            ('help_mod','x_main',0,'br','x_main',0,14,'HELP_MOD','doc/help.php','Ajuda para este módulo','Ajuda',NULL,NULL,NULL,1,0),
            ('help_ndx','x_main',0,'br','x_main',0,15,'HELP','doc/help.php?mode=global','Consultar documentação','Manual',NULL,NULL,NULL,1,0),
            ('impexp',NULL,0,'br','main',0,8,'IMPEXP','index.php?mode=impexp','Controle de Operações: Importação, exportação, carga, backup, etc.','Operações','glyphicon glyphicon-wrench',NULL,NULL,1,0),
            ('IMP_ACSEAL','MIMP_SEAL',2,'br','impexp',0,200,'IMP_ACSEAL','impexp_seal_accelerators','Acelerador de Selos','Acelerador de Selos',NULL,NULL,'impexp',0,0),
            ('IMP_BACKUP','impexp',1,'br','impexp',0,120,'IMP_BACKUP','impexp_backup','Geração de backup','Backup',NULL,NULL,'impexp',0,0),
            ('IMP_BEBLUE','MIE_IDBDB',2,'br','impexp',0,400,'IMP_BEBLUE','impexp_beblue','Integração Beblue','Integração Beblue',NULL,NULL,'impexp',0,0),
            ('IMP_CLUST','impexp',1,'br','impexp',0,220,'IMP_CLUST','/moderator-cgi/control_panel?mode=farm','Controle dos processadores no cluster','Cluster',NULL,NULL,'impexp',0,0),
            ('IMP_CONSIN','impexp',1,'br','impexp',0,43,'IMP_CONSIN','impexp_consinco','Integração Consinco','Integração Consinco',NULL,NULL,'impexp',0,0),
            ('IMP_CPANEL','impexp',1,'br','impexp',0,200,'IMP_CPANEL','/moderator-cgi/control_panel?action=start&theme={theme}','Controle e acompanhamento do sistema','Painel',NULL,NULL,'impexp',0,0),
            ('IMP_CTP06','impexp',1,'br','impexp',0,3510,'IMP_CTP06','impexp_cotepe06','Ato COTEPE 06/08','Ato COTEPE 06/08',NULL,NULL,'impexp',0,0),
            ('IMP_CVENDA','MIE_IDBDB',2,'br','impexp',0,600,'IMP_CVENDA','impexp_cvenda','Integra??o CresceVendas','Integra??o CresceVendas',NULL,NULL,'impexp',0,0),
            ('IMP_DB_DB','impexp',1,'br','impexp',0,180,'IMP_DB_DB','impexp_db_db','Comunicação banco a banco','Banco a Banco',NULL,NULL,'impexp',0,0),
            ('IMP_DEL','impexp',1,'br','impexp',0,155,'IMP_DEL','impexp_delete','Exclusão de dados não mais utilizados','Exclusão de Movimento',NULL,NULL,'impexp',0,0),
            ('IMP_DIGITA','impexp',1,'br','impexp',0,3500,'IMP_DIGITA','impexp_digital','Arquivo Digital','Arquivo Digital',NULL,NULL,'impexp',0,0),
            ('IMP_DIRCMD','impexp',1,'br','impexp',0,75,'IMP_SEND','impexp_direct_command','Envio de comando a PDVs para execução imediata','Comando Imediato',NULL,NULL,'impexp',0,0),
            ('IMP_DOC','impexp',1,'br','impexp',0,42,'IMP_DOC','impexp_doc_load','Importação de Nota Fiscal Eletrônica','Importação de Nota Eletrônica',NULL,NULL,'impexp',0,0),
            ('IMP_ECFSTS','impexp',1,'br','impexp',0,25,'IMP_ECFSTS','impexp_ecf_sts','Situação dos ECFs','Status ECF',NULL,NULL,'impexp',0,0),
            ('IMP_EXP87','MIE_EXPORT',2,'br','impexp',0,300,'IMP_EXP87','impexp_export87_db2db','Integração Banco a Banco Export87','Integração Banco a Banco Export87',NULL,NULL,'impexp',0,0),
            ('IMP_EXPDIR','impexp',1,'br','impexp',0,170,'IMP_EXPDIR','/exp/','Download de arquivos exportados','Diretório de exportação',NULL,NULL,'impexp',0,0),
            ('IMP_EXPGMC','MIE_OTHER',2,'br','impexp',0,100,'IMP_EXPGMC','impexp_export_gemco','Integração GEMCO','Integração GEMCO',NULL,NULL,'impexp',0,1),
            ('IMP_EXPORT','impexp',1,'br','impexp',0,100,'IMP_EXPORT','impexp_export','Exportação de arquivos','Exportação',NULL,NULL,'impexp',0,0),
            ('IMP_FILLOJ','impexp',1,'br','impexp',0,210,'IMP_FILLOJ','/moderator-cgi/control_panel?mode=queues','Mensagens enfileiradas, por loja','Filas por Loja',NULL,NULL,'impexp',0,0),
            ('IMP_GAM',NULL,1,'br','impexp',0,165,'IMP_GAM','impexp_gam','Gerador de Arquivos MagnÃ©ticos das operaÃ§Ãµes com combustÃ­veis (GAM)','GAM',NULL,NULL,NULL,NULL,NULL),
            ('IMP_GSEAL','MIMP_SEAL',2,'br','impexp',0,100,'IMP_GSEAL','impexp_pos_group_seal','Grupo PDV - Selos','Grupo PDV - Selos',NULL,NULL,'impexp',0,0),
            ('IMP_ISEAL','MIMP_SEAL',2,'br','impexp',0,300,'IMP_ISEAL','impexp_input_seal','Administra??o de Selos','Administra??o de Selos',NULL,NULL,'impexp',0,0),
            ('IMP_LOAD','impexp',1,'br','impexp',0,40,'IMP_LOAD','impexp_load','Importação de arquivo','Importação',NULL,NULL,'impexp',0,0),
            ('IMP_MKADD','impexp',1,'br','impexp',0,205,'IMP_MKADD','mk_import_adder','Importação e Inicialização de Acumuladores','Importação de Acumuladores',NULL,NULL,'impexp',0,0),
            ('IMP_NOTIF','impexp',1,'br','impexp',0,230,'IMP_NOTIF','impexp_notification','Controle de Operadores','Operadores',NULL,NULL,'impexp',0,0),
            ('IMP_PDVRMS','MIE_EXPORT',2,'br','impexp',0,400,'IMP_PDVRMS','impexp_pdv_rms','Integração de PDV x RMS Sales','Integração de PDV x RMS Sales',NULL,NULL,'impexp',0,0),
            ('IMP_POSINS','impexp',1,'br','impexp',0,130,'IMP_POSINS','impexp_posinstall','Criação de pacotes de instalação de PDVs','Pacotes',NULL,NULL,'impexp',0,0),
            ('IMP_POSSTS','impexp',1,'br','impexp',0,20,'IMP_POSSTS','impexp_pos_sts','Situação dos PDVs','Status PDV',NULL,NULL,'impexp',0,0),
            ('IMP_QUEUES','impexp',1,'br','impexp',0,140,'IMP_QUEUES','impexp_queues','Controle de filas','Filas',NULL,NULL,'impexp',0,0),
            ('IMP_REPR','impexp',1,'br','impexp',0,150,'IMP_REPR','impexp_reprocess','Reprocessamento de movimentos já recebidos','Reprocessamento',NULL,NULL,'impexp',0,0),
            ('IMP_REQUES','impexp',1,'br','impexp',0,190,'IMP_REQUES','impexp_request','Situação de comandas','Comandas',NULL,NULL,'impexp',0,0),
            ('IMP_RMSDB','MIE_IDBDB',2,'br','impexp',0,200,'IMP_RMSDB','impexp_rms_integration','Integração RMS Banco a banco','Integração RMS',NULL,NULL,'impexp',0,0),
            ('IMP_SB1','MIE_IDBDB',2,'br','impexp',0,500,'IMP_SB1','impexp_sb1','Integração Business One','Integração SB1',NULL,NULL,'impexp',0,0),
            ('IMP_SCALE','impexp',1,'br','impexp',0,110,'IMP_SCALE','impexp_scale','Exportação de arquivos de carga de balanças e verificadores de preços','Balanças / Verificadores',NULL,NULL,'impexp',0,0),
            ('IMP_SEND','impexp',1,'br','impexp',0,50,'IMP_SEND','impexp_send','Envio de dados a PDVs','Envio',NULL,NULL,'impexp',0,0),
            ('IMP_SESSIO','impexp',1,'br','impexp',0,30,'IMP_SESSIO','impexp_session','Sessões','Lista de Sessões',NULL,NULL,'impexp',0,0),
            ('IMP_SINTEG','impexp',1,'br','impexp',0,160,'IMP_SINTEG','impexp_sintegra','Excrituração e emissão de documentos fiscais por processamento de dados','Sintegra',NULL,NULL,'impexp',0,0),
            ('IMP_SPED','MIE_EXPORT',2,'br','impexp',0,100,'IMP_SPED','impexp_sped','SPED','SPED',NULL,NULL,'impexp',0,0),
            ('IMP_SPEDDF','MIE_EXPORT',2,'br','impexp',0,200,'IMP_SPEDDF','impexp_sped_df','SPED_DF','SPED_DF',NULL,NULL,'impexp',0,0),
            ('IMP_STATUS','impexp',1,'br','impexp',0,10,'IMP_STATUS','impexp_status','Lista de Transações','Status',NULL,NULL,'impexp',0,0),
            ('IMP_SVTSVC','MIMP_SVTSV',2,'br','impexp',0,300,'IMP_SVTSVC','impexp_servertoserver_conf','Configuração Servidor Local','Configuração',NULL,NULL,'impexp',0,0),
            ('IMP_SVTSVE','MIMP_SVTSV',2,'br','impexp',0,100,'IMP_SVTSVE','impexp_servertoserver_send','Envio Servidor Local','Envio',NULL,NULL,'impexp',0,0),
            ('IMP_SVTSVM','MIMP_SVTSV',2,'br','impexp',0,200,'IMP_SVTSVM','impexp_servertoserver_moni','Monitoramento Servidor Local','Monitoramento',NULL,NULL,'impexp',0,0),
            ('IMP_TICKET','impexp',1,'br','impexp',0,1865,'IMP_TICKET','impexp_ticket','Administração de Filas','Filas de Vendas',NULL,NULL,'impexp',0,0),
            ('IMP_WEBSRV','impexp',1,'br','impexp',0,15,'IMP_WEBSRV','impexp_web_service','Status do Web Service','Web Service',NULL,NULL,'impexp',0,0),
            ('INTEGRATI','MIE_IDBDB',2,'br','impexp',0,300,'INTEGRATI','impexp_integration','Integração','Integração',NULL,NULL,'impexp',0,1),
            ('IZIO_ENTR','MPART_IZIO',2,'br','partner',0,100,'IZIO_ENTR','izio_entries','Envio IZIO','Envio IZIO',NULL,NULL,'partner',0,1),
            ('IZIO_INFO','MPART_IZIO',2,'br','partner',0,300,'IZIO_INFO','izio_info_view','Informa??es IZIO','Informa??es IZIO',NULL,NULL,'partner',0,1),
            ('IZIO_PARAM','MPART_IZIO',2,'br','partner',0,200,'IZIO_PARAM','izio_param','Configura??o IZIO','Configura??o IZIO',NULL,NULL,'partner',0,1),
            ('logout',NULL,0,'br','main',0,585,'LOGOUT','index.php?mode=logout','Encerrar esta sessão','Sair',NULL,NULL,NULL,1,0),
            ('MAMO_DEP','amount',1,'br','amount',0,800,'MAMO_DEP','#','Vendas por Departamento','Departamentos',NULL,'this','amount',2,0),
            ('MAMO_DSC','amount',1,'','amount',0,675,'MAMO_DSC','#','Relatórios de descontos','Descontos',NULL,'this','amount',2,0),
            ('MAMO_ESTAT','amount',1,'','amount',0,8500,'MAMO_ESTAT','#','Estatísticas Diversas','Estatísticas',NULL,'this','amount',2,0),
            ('MAMO_FISC','amount',1,'br','amount',0,1000,'MAMO_FISC','#','Impostos e bases de cálculo','Impostos',NULL,'this','amount',2,0),
            ('MAMO_ITEM','amount',1,'br','amount',0,900,'MAMO_ITEM','#','Vendas por Item','Itens',NULL,'this','amount',2,0),
            ('MAMO_MEDIA','amount',1,'br','amount',0,500,'MAMO_MEDIA','#','Finalizações, resumo de cartões, etc.','Mais Finalizadoras',NULL,'this','amount',2,0),
            ('MAMO_OPER','amount',1,'br','amount',0,600,'MAMO_OPER','#','Operadores, Produtividade, etc.','Funcionários',NULL,'this','amount',2,0),
            ('MAMO_OTHER','amount',1,'','amount',0,687,'MAMO_OTHER','#','Recebimento de pagamentos, saques, etc.','Outras Operações',NULL,'this','amount',2,0),
            ('MAMO_RTN','amount',1,'br','amount',0,700,'MAMO_RTN','#','Devoluções, trocas, reembolsos','Devoluções',NULL,'this','amount',2,0),
            ('MAMO_TCKT','amount',1,'','amount',0,385,'MAMO_TCKT','#','Consulta de diversos tipos de transações','Vendas por Tipo',NULL,'this','amount',2,0),
            ('MAMO_TOTAL','amount',1,'br','amount',0,1100,'MAMO_TOTAL','#','Comparação entre valores','Verificações',NULL,'this','amount',2,0),
            ('MIE_EXPORT','impexp',1,'','impexp',0,45,'MIE_EXPORT','#','Exportação de movimentos, arquivos fiscais, etc.','Exportações',NULL,'this','amount',2,0),
            ('MIE_IDBDB','impexp',1,'','impexp',0,1550,'MIE_IDBDB','#','Integrações','Integrações',NULL,'this','impexp',2,0),
            ('MIE_OTHER','impexp',1,'','impexp',0,48,'MIE_OTHER','#','Operações batch','Outras Operações',NULL,'this','amount',2,0),
            ('MIE_QUEUE','impexp',1,'','impexp',0,47,'MIE_QUEUE','#','Filas de vendas, de mensagens, etc.','Filas',NULL,'this','amount',2,0),
            ('MIMP_SEAL','impexp',1,'br','impexp',0,3610,'MIMP_SEAL','#','Selos','Selos',NULL,'this','impexp',2,0),
            ('MIMP_SVTSV','impexp',1,'br','impexp',0,49,'MIMP_SVTSV','#','Exportação Servidor Local','Exportação Servidor Local',NULL,'this','impexp',2,0),
            ('MPART_CUS','partner',1,'','partner',0,300,'MPART_CUS','#','Parceiro DBOnline','DBOnline',NULL,'this','partner',2,0),
            ('MPART_IZIO','partner',1,'','partner',0,400,'MPART_IZIO','#','Parceiro IZIO','IZIO',NULL,'this','partner',2,1),
            ('MPART_MTRD','partner',1,'','partner',0,500,'MPART_MTRD','#','Parceiro MINUTRADE','MINUTRADE',NULL,'this','partner',2,1),
            ('MPART_SCA','partner',1,'','partner',0,200,'MPART_SCA','#','Parceiro Scanntech','Scanntech',NULL,'this','partner',2,0),
            ('MPLU_AUX','plu',1,'','plu',0,382,'MPLU_AUX','#','Tipos de preços, serviços, etiquetas, etc.','Tabelas Auxiliares',NULL,'this','plu',2,0),
            ('MPLU_CEL','plu',1,'','plu',0,329,'MPLU_CEL','#','Dados para recarga de celulares','Celular',NULL,'this','plu',2,0),
            ('MPLU_DEPT','plu',1,'','plu',0,359,'MPLU_DEPT','#','Manutenção da tabela de departamentos','Departamentos',NULL,'this','plu',2,0),
            ('MPLU_PLAN','plu',1,'br','plu',0,269,'MPLU_PLAN','#','Planos, parcelas, etc.','Planos',NULL,'this','plu',2,0),
            ('MPLU_PROMO','plu',1,'','plu',0,55,'MPLU_PROMO','#','Promoções e campanhas','Promoções',NULL,'this','plu',2,0),
            ('MPLU_REST','plu',1,'','plu',0,374,'MPLU_REST','#','Dados para restaurantes','Restaurante',NULL,'this','plu',2,0),
            ('MPLU_SELF','plu',1,'','plu',0,3850,'MPLU_SELF','#','Self-Checkout','Self-Checkout',NULL,'this','plu',2,0),
            ('MTRD_PARAM','MPART_MTRD',2,'br','partner',0,100,'MTRD_PARAM','minutrade_param','Configura??o MINUTRADE','Configura??o MINUTRADE',NULL,NULL,'partner',0,1),
            ('next_group','x_main',0,'br','x_main',0,98,'NEXT','index.php?mode=next','Mostrar outro menu','Mais ...',NULL,NULL,NULL,1,0),
            ('nfe',NULL,0,'br','main',0,9700,'NFE','index.php?mode=nfe','NFe','NFe','img/nfe.png',NULL,NULL,1,1),
            ('NFE_STATUS','nfe',1,'br','nfe',0,100,'NFE_STATUS','nfe_status','Status de Transações','Status',NULL,NULL,'nfe',0,1),
            ('partner',NULL,0,'br','main',0,9800,'PARTNER','index.php?mode=partner','Tela de Parceiros Conecto','Parceiros',NULL,NULL,NULL,1,1),
            ('PART_VIEW','partner',1,'br','partner',0,100,'PARTNER','partner_view','Tela de Parceiros Conecto','Parceiros',NULL,NULL,'partner',0,0),
            ('PHARMACY',NULL,0,'br','main',0,87,'PHARMACY','index.php?mode=pharmacy','Farmácia','Farmácia','img/pharmacy.gif',NULL,NULL,1,1),
            ('PHA_CTRLD','PHA_SNGPC',2,'br','pharmacy',0,100,'PHA_CTRLD','pharmacy_controlled_substances','Registro de Medicamentos controlados','Registro de Controlados',NULL,NULL,'pharmacy',0,0),
            ('PHA_FARMS','PHARMACY',1,'br','PHARMACY',0,200,'PHA_FARMS','pharmacy_pre_auth_farmaseg','Pré Autorização FarmaSeg','Pré Autorização FarmaSeg',NULL,NULL,'PHARMACY',0,0),
            ('PHA_FCARD','pharmacy',1,'br','pharmacy',0,600,'PHA_FCARD','pharmacy_funcional_card','Funcional Card','Funcional Card',NULL,NULL,'pharmacy',0,0),
            ('PHA_IMP','pharmacy',1,'br','pharmacy',0,250,'PHA_IMP','pharmacy_impexp_doc_load','Importa??o de Nota Fiscal Eletr?nica Farm?cia','Importa??o de Nota Eletr?nica',NULL,NULL,'pharmacy',0,0),
            ('PHA_MAKER','pharmacy',1,'br','pharmacy',0,400,'PHA_MAKER','pharmacy_maker','Convênios','Convênios',NULL,NULL,'pharmacy',0,0),
            ('PHA_ORDER','PHARMACY',1,'br','PHARMACY',0,100,'PHA_ORDER','pharmacy_ticket','Visualização de pedidos','Pedidos',NULL,NULL,NULL,0,0),
            ('PHA_PBM','pharmacy',1,'br','pharmacy',0,300,'PHA_PBM','pharmacy_pbm','PBMs','PBMs',NULL,NULL,'pharmacy',0,0),
            ('PHA_PBMMK','pharmacy',1,'br','pharmacy',0,500,'PHA_PBMMK','pharmacy_pbm_maker','Convênios por PBMs','Convênios por PBMs',NULL,NULL,'pharmacy',0,0),
            ('PHA_SNGPC','pharmacy',1,'','pharmacy',0,700,'PHA_SNGPC','#','Sistema Nacional de Gerenciamento de Produtos Controlados','SNGPC',NULL,'this','pharmacy',2,0),
            ('PHA_STSAN','PHA_SNGPC',2,'br','pharmacy',0,50,'PHA_STSAN','pharmacy_send_status','Status de Envio ANVISA','Status de envio',NULL,NULL,'pharmacy',0,0),
            ('plu',NULL,0,'br','main',0,80,'PLU','index.php?mode=plu','Manutenção do Cadastro de Itens','PLU','glyphicon glyphicon-barcode',NULL,NULL,1,0),
            ('PLU_ADM','PLU',1,'br','PLU',0,260,'PLU_ADM','plu_adm_prices','AdministraÃ§Ã£o de PreÃ§o','AdministrÃ§Ã£o de PreÃ§os',NULL,NULL,'plu',0,0),
            ('PLU_ADMSPTC','MPLU_PLAN',2,'br','plu',0,395,'PLU_ADMSPT','plu_plan_admin_code','Cadastro de Código de Administradora','Cadastro de Código de Administradora',NULL,NULL,'plu',0,0),
            ('PLU_ADMSPTT','MPLU_PLAN',2,'br','plu',0,495,'PLU_ADMSPT','plu_plan_admin_type','Cadastro de Tipo de Financiamento','Cadastro de Tipo de Financiamento',NULL,NULL,'plu',0,0),
            ('PLU_BUDGET','plu',1,'br','plu',0,3350,'PLU_BUDGET','plu_budget','Metas','Metas',NULL,NULL,'plu',0,0),
            ('PLU_CEST','plu',1,'br','plu',0,127,'PLU_CEST','plu_cest','Manutenção de CEST','CEST',NULL,NULL,'plu',0,0),
            ('PLU_CHECK','plu',1,'br','plu',0,3750,'PLU_CHECK','plu_checking','Checagem de PLU','Checagem de PLU',NULL,NULL,'plu',0,0),
            ('PLU_COMPET','plu',1,'br','plu',0,3250,'PLU_COMPET','plu_compet','Concorrentes','Concorrentes',NULL,NULL,'plu',0,0),
            ('PLU_CPRE','plu',1,'br','plu',0,410,'PLU_CPRE','plu_cell_prefix','Prefixos de Celulares','Prefixos de Celulares',NULL,NULL,'plu',0,0),
            ('PLU_DEPTRE','MPLU_DEPT',2,'br','plu',0,100,'PLU_DEPTRE','plu_depts','Estrutura de Departamentos','Estrutura de Departamentos',NULL,NULL,'plu',0,0),
            ('PLU_DEPTREE','plu',1,'br','plu',0,100,'PLU_DEPTRE','plu_depts','Estrutura de Departamentos','Estrutura de Departamentos',NULL,NULL,'plu',0,0),
            ('PLU_DEPTS','plu',1,'br','plu',0,90,'PLU_DEPTS','plu_depts','Manutenção de Departamentos','Departamentos',NULL,NULL,'plu',0,0),
            ('PLU_DOTZ','MPLU_PROMO',2,'br','plu',0,300,'PLU_DOTZ','plu_dotz','Dotz por Item','Dotz por Item',NULL,NULL,'plu',0,0),
            ('PLU_DPSITM','MPLU_AUX',2,'br','plu',0,275,'PLU_DPSITM','plu_group_deposit_item','Itens por grupos de vasilhame','Itens por grupos de vasilhames',NULL,NULL,'plu',0,0),
            ('PLU_FSIT','plu',1,'br','plu',0,143,'PLU_FSIT','plu_fiscal_situation','Manutenção de situações fiscais','Situações Fiscais',NULL,NULL,'plu',0,0),
            ('PLU_GROUP','plu',1,'br','plu',0,250,'PLU_GROUP','plu_group','Grupo de itens','Grupo de itens',NULL,NULL,'plu',0,0),
            ('PLU_GRPDPS','MPLU_AUX',2,'br','plu',0,250,'PLU_GRPDPS','plu_group_deposit','Grupos Vasilhames','Grupos Vasilhames',NULL,NULL,'plu',0,0),
            ('PLU_GRPOBL','MPLU_AUX',2,'br','plu',0,100,'PLU_GRPOBL','plu_group_oblata','Grupos Promocionais','Grupos promocionais',NULL,NULL,'plu',0,0),
            ('PLU_GRPSC','plu',1,'br','plu',0,254,'PLU_GRPSC','plu_group_screen','Grupos para tela','Grupos para tela',NULL,NULL,'plu',0,0),
            ('PLU_INFN',NULL,1,'br','plu',0,3530,'PLU_INFN','plu_info_nutrition','Informações Nutricionais','Informações Nutricionais',NULL,NULL,NULL,0,0),
            ('PLU_ITEMS','plu',1,'br','plu',0,20,'PLU_ITEMS','plu_items','Manutenção de Produtos','Produtos',NULL,NULL,'plu',0,0),
            ('PLU_KITS','plu',1,'br','plu',0,80,'PLU_KITS','plu_kits','Consulta de Kits','Kits',NULL,NULL,'plu',0,0),
            ('PLU_LABEL','plu',1,'br','plu',0,180,'PLU_LABEL','plu_label','Manutenção de Tipos de Etiqueta','Tipos de Etiquetas',NULL,NULL,'plu',0,0),
            ('PLU_LIST','plu',1,'br','plu',0,200,'PLU_LIST','plu_list','Listagem de Produtos','Listagens',NULL,NULL,'plu',0,0),
            ('PLU_MAKERS','plu',1,'br','plu',0,110,'PLU_MAKERS','plu_makers','Manutenção de Fabricantes','Fabricantes',NULL,NULL,'plu',0,0),
            ('PLU_NCM','plu',1,'br','plu',0,125,'PLU_NCM','plu_ncm','Manutenção de NCM','NCM',NULL,NULL,'plu',0,0),
            ('PLU_OBDOTZ','plu',1,'br','plu',0,3650,'PLU_OBDOTZ','plu_oblata_dotz','Campanha Dotz','Campanha Dotz',NULL,NULL,'plu',0,0),
            ('PLU_OBITEM','MPLU_AUX',2,'br','plu',0,300,'PLU_OBITEM','plu_oblata_item','Permissão Itens Campanha','Permissão Itens Campanha',NULL,NULL,'plu',0,0),
            ('PLU_OBLATA','plu',1,'br','plu',0,75,'PLU_OBLATA','plu_oblata','Promoções Especiais','Campanhas',NULL,NULL,'plu',0,0),
            ('PLU_OBLFDL','plu',1,'br','plu',0,3950,'PLU_OBLFDL','plu_oblata_fidelity','Campanha Fidelidade','Campanha Fidelidade',NULL,NULL,'plu',0,0),
            ('PLU_OBLITM','MPLU_AUX',2,'br','plu',0,200,'PLU_OBLITM','plu_group_oblata_item','Itens por grupos promocionais','Itens por grupos promocionais',NULL,NULL,'plu',0,0),
            ('PLU_OBLTKT','plu',1,'br','plu',0,77,'PLU_OBLTKT','plu_oblata_extra_ticket','Formatos de comprovantes de campanha','Comprovantes de Campanha',NULL,NULL,'plu',0,0),
            ('PLU_OPER','plu',1,'br','plu',0,390,'PLU_OPER','plu_operator','Cadastro de Operadoras','Cadastro de Operadoras',NULL,NULL,'plu',0,0),
            ('PLU_ORDER','plu',1,'br','plu',0,145,'PLU_ORDER','plu_order_type','Tipo de Destino','Tipo de Destino',NULL,NULL,'plu',0,0),
            ('PLU_PACK','plu',1,'br','plu',0,85,'PLU_PACK','plu_pack','Manutenção de packs','Packs',NULL,NULL,'plu',0,0),
            ('PLU_PLAN','MPLU_PLAN',2,'br','plu',0,270,'PLU_PLAN','plu_plan','Manutenção de Planos','Planos',NULL,NULL,'plu',0,0),
            ('PLU_PLDEPT','MPLU_PLAN',2,'br','plu',0,290,'PLU_PLDEPT','plu_plan_department','Planos por departamento','Planos por departamento',NULL,NULL,'plu',0,0),
            ('PLU_PLUTY','plu',1,'br','plu',0,909,'PLU_PLUTY','plu_plu_type','Tipo de PLU','Tipo de PLU',NULL,NULL,'plu',0,0),
            ('PLU_PQSITM','plu',1,'br','plu',0,3575,'PLU_PQSITM','plu_price_quick_search','Pesquisa R?pida de Pre?o','Pesquisa R?pida de Pre?o',NULL,NULL,'plu',0,1),
            ('PLU_PRCUPD','plu',1,'br','plu',0,50,'PLU_PRCUPD','plu_pricing_update','Alteração de Preços','Alteração de Preços',NULL,NULL,'plu',0,0),
            ('PLU_PRICES','plu',1,'br','plu',0,150,'PLU_PRICES','plu_prices','Manutenção de Tipos de Preços','Tipos de Preço',NULL,NULL,'plu',0,0),
            ('PLU_PRM_ITM','MPLU_PROMO',2,'br','plu',0,100,'PLU_PRM_IT','plu_promotion_item','Items Campanhas','Items Campanhas',NULL,NULL,'plu',0,0),
            ('PLU_PROMO','plu',1,'br','plu',0,70,'PLU_PROMO','plu_promotion','Campanhas Promocionais','Promoções',NULL,NULL,'plu',0,0),
            ('PLU_PROMOA','MPLU_PROMO',2,'br','plu',0,200,'PLU_PROMOA','plu_label_promotion','Campanha Etiqueta Relâmpago','Etiqueta Relâmpago',NULL,NULL,'plu',0,0),
            ('PLU_PSPLIT','MPLU_PLAN',2,'br','plu',0,295,'PLU_PSPLIT','plu_plan_split_amount','Exceções de planos','Exceções de planos',NULL,NULL,'plu',0,0),
            ('PLU_PSTORE','MPLU_PLAN',2,'br','plu',0,280,'PLU_PSTORE','plu_plan_store','Plano por Loja','Plano por Loja',NULL,NULL,'plu',0,0),
            ('PLU_PSWGHT','plu',1,'br','plu',0,3600,'PLU_PSWGHT','plu_selfcheckout_weight','Varia??o de Peso','Varia??o de Peso',NULL,NULL,'plu',0,0),
            ('PLU_RECMES','plu',1,'br','plu',0,3550,'PLU_RECMES','plu_recipe_message','Manutenção de Mensagem da Receita','Mensagem da Receita',NULL,NULL,'plu',0,0),
            ('PLU_RES','plu',1,'br','plu',0,3450,'PLU_RES','plu_research','Pesquisas','Pesquisas',NULL,NULL,'plu',0,0),
            ('PLU_SCREEN','plu',1,'br','plu',0,256,'PLU_SCREEN','plu_screen','Itens para tela','Itens para tela',NULL,NULL,'plu',0,0),
            ('PLU_SEARCH','plu',1,'br','plu',0,52,'PLU_SEARCH','plu_search','Consulta de itens em campanhas e planos','Consulta de Itens',NULL,NULL,'plu',0,0),
            ('PLU_SERVIC','plu',1,'br','plu',0,3150,'PLU_SERVIC','plu_service','Manutenção de Seviços','Serviço',NULL,NULL,'plu',0,0),
            ('PLU_SKUSTO','plu',1,'br','plu',0,170,'PLU_SKUSTO','plu_sku','Consulta de SKU por Loja','SKU Loja',NULL,NULL,'plu',0,0),
            ('PLU_SLFCKI','MPLU_SELF',2,'br','plu',0,100,'PLU_SLFCKI','plu_self-checkout_check_items','Verifica??o de Itens Self-Checkout','Verifica??o de Itens Self-Checkout',NULL,NULL,'plu',0,0),
            ('PLU_SLFCNF','MPLU_SELF',2,'br','plu',0,200,'PLU_SLFCNF','plu_self-checkout_param','Par?metros Self-Checkout','Par?metros Self-Checkout',NULL,NULL,'plu',0,0),
            ('PLU_SPLIT','MPLU_PLAN',2,'br','plu',0,275,'PLU_SPLIT','plu_plan_split','Parcelas','Parcelas',NULL,NULL,'plu',0,0),
            ('PLU_SRVTYP','plu',1,'br','plu',0,3100,'PLU_SRVTYP','plu_service_type','Manutenção de Tipo de Seviço','Tipo de Serviço',NULL,NULL,'plu',0,0),
            ('PLU_STOCK','plu',1,'br','plu',0,60,'PLU_STOCK','plu_stock','Manutenção de Estoque','Estoque',NULL,NULL,'plu',0,0),
            ('PLU_STOCST','plu',1,'br','plu',0,35,'PLU_STOCST','plu_stocst','Manutenção de Custos','Custos',NULL,NULL,'plu',0,0),
            ('PLU_STOLBL','plu',1,'br','plu',0,190,'PLU_STOLBL','plu_stolbl','Etiquetas por Loja','Etiquetas',NULL,NULL,'plu',0,0),
            ('PLU_STOPRC','plu',1,'br','plu',0,30,'PLU_STOPRC','plu_stoprc','Manutenção de Preços','Preços',NULL,NULL,'plu',0,0),
            ('PLU_STOSTP','plu',1,'br','plu',0,40,'PLU_STOSTP','plu_stostp','Manutenção de Preços por Quantidade','Preços/Qtde',NULL,NULL,'plu',0,0),
            ('PLU_TARES','plu',1,'br','plu',0,160,'PLU_TARES','plu_tares','Manutenção de Tipos de Taras','Taras',NULL,NULL,'plu',0,0),
            ('PLU_TAXES','plu',1,'br','plu',0,120,'PLU_TAXES','plu_taxes','Manutenção de Impostos','Impostos',NULL,NULL,'plu',0,0),
            ('PLU_TYPES','plu',1,'br','plu',0,140,'PLU_TYPES','plu_types','Manutenção de Tipos de Impostos','Tipos de Impostos',NULL,NULL,'plu',0,0),
            ('PLU_UNITS','plu',1,'br','plu',0,130,'PLU_UNITS','plu_units','Manutenção de Unidades','Unidades',NULL,NULL,'plu',0,0),
            ('POSV','status',1,'br','status',0,187,'POSV','status_pos_program','Versão do Venditor dos PDVs','Versão PDV',NULL,NULL,'status',0,0),
            ('POSW','status',1,'br','status',0,175,'POSW','/moderator-cgi/poswizard?mode=view','Status de PDVs','PDV',NULL,NULL,'status',0,0),
            ('PRM_RMS','store',1,'br','store',0,342,'PRM_RMS','store_parameter_rms','Parâmetros RMS','Parâmetros RMS',NULL,NULL,'store',0,1),
            ('promotion',NULL,0,'br','main',0,81,'PROMOTION','index.php?mode=promotion','Cadastro e Configura??es de Promo??es','Campanhas','glyphicon glyphicon-tags',NULL,NULL,1,0),
            ('PROMO_EXT','promotion',1,'br','promotion',0,100,'PROMO_EXT','promotion_external','Campanhas Externas','Campanhas Externas',NULL,NULL,'promotion',0,0),
            ('PROMO_SAMO','promotion',1,'br','promotion',0,200,'PROMO_SAMO','promotion_external_store_amount','Campanhas Externas - Saldo por Loja','Campanhas Externas - Saldo por Loja',NULL,NULL,'promotion',0,0),
            ('PROMO_TKT','promotion',1,'br','promotion',0,150,'PROMO_TKT','promotion_ext_status','Vendas promocionais','Vendas promocionais',NULL,NULL,'promotion',0,0),
            ('REENV_NFCE','MIE_OTHER',2,'br','impexp',0,200,'REENV_NFCE','impexp_reenvio_nfce','Reenvio de NFCE','Reenvio de NFCE',NULL,NULL,'impexp',0,0),
            ('request',NULL,0,'br','main',0,7,'REQUEST','index.php?mode=request','Operações de Pedido','Pedido','glyphicon glyphicon-list-alt',NULL,NULL,1,0),
            ('REQ_CREATE','request',1,'br','request',0,100,'REQ_CREATE','request_create','Pré Venda','Pedido',NULL,NULL,'request',0,0),
            ('REQ_CSLALC','request',1,'br','request',0,500,'REQ_CSLALC','request_allocate','Consulta Empenho de Estoque','Consulta Empenho de Estoque',NULL,NULL,'request',0,0),
            ('REQ_CSLSTO','request',1,'br','request',0,400,'REQ_CSLSTO','request_stock','Consulta Estoque','Consulta de Estoque',NULL,NULL,'request',0,0),
            ('REQ_RELCKE','request',1,'br','request',0,300,'REQ_RELCKE','request_clerk','Relatório de vendedor','Relatório de Vendedor',NULL,NULL,'request',0,0),
            ('REQ_RELCST','request',1,'br','request',0,200,'REQ_RELCST','request_customer','Relatório de cliente','Relatório de Cliente',NULL,NULL,'request',0,0),
            ('restaurant',NULL,0,'br','main',0,2140,'RESTAURANT','index.php?mode=restaurant','Operações de Restaurante','Restaurante',NULL,NULL,NULL,1,1),
            ('RES_ADDGRO','restaurant',1,'br','restaurant',0,300,'RES_ADDGRO','restaurant_add_group','Cadastro de Grupos de Itens adicionais e associações com os adicionais','Grupos de Itens Adicionais',NULL,NULL,'restaurant',0,0),
            ('RES_ATTPL','restaurant',1,'br','restaurant',0,900,'RES_ATTPL','restaurant_attendance_place','Manutenção de Local de Atendimento','Local de Atendimento',NULL,NULL,'restaurant',0,0),
            ('RES_ATTPR','restaurant',1,'br','restaurant',0,600,'RES_ATTPR','restaurant_attendance_prof','Manutenção de Perfil de Atendimento','Perfil de Atendimento',NULL,NULL,'restaurant',0,0),
            ('RES_DBDB','restaurant',1,'br','restaurant',0,1100,'RES_DBDB','restaurant_db_db','Comunicação Banco a Banco','Banco a Banco',NULL,NULL,'restaurant',0,0),
            ('RES_ITEGRO','restaurant',1,'br','restaurant',0,400,'RES_ITEGRO','restaurant_item_x_group','Associação de Itens com os Grupo de Adicionais','Itens x Grupo de Adicionais',NULL,NULL,'restaurant',0,0),
            ('RES_ITEM','restaurant',1,'br','restaurant',0,200,'RES_ITEM','restaurant_item','Manutenção dos Itens, associação com os exclusos, etc','Cadastro de Itens',NULL,NULL,'restaurant',0,0),
            ('RES_MENUTR','restaurant',1,'br','restaurant',0,100,'RES_MENUTR','restaurant_menus','Estrutura de Menus','Estrutura de Menus',NULL,NULL,'restaurant',0,0),
            ('RES_PLUPLA','restaurant',1,'br','restaurant',0,1000,'RES_PLUPLA','restaurant_plu_place','Associação de Itens com Locais de Atendimento','Itens x Locais de Atendimento',NULL,NULL,'restaurant',0,0),
            ('RES_PRINT','restaurant',1,'br','restaurant',0,700,'RES_PRINT','restaurant_printer','Manutenção de Impressora','Impressora',NULL,NULL,'restaurant',0,0),
            ('RES_PRODPL','restaurant',1,'br','restaurant',0,800,'RES_PRODPL','restaurant_prodution_place','Manutenção de Local de Produção','Local de Produção',NULL,NULL,'restaurant',0,0),
            ('RES_PROF','restaurant',1,'br','restaurant',0,500,'RES_PROF','restaurant_profile','Manutenção de Perfil','Perfil',NULL,NULL,'restaurant',0,0),
            ('SCASTATUS','MPART_SCA',2,'br','partner',0,500,'SCASTATUS','scanntech_status','Status do serviço Scanntech','Status Serviço',NULL,NULL,'partner',0,0),
            ('SCA_CONF','MPART_SCA',2,'br','partner',0,400,'SCA_CONF','scanntech_param','Configuração Scanntech','Configuração',NULL,NULL,'partner',0,0),
            ('SCA_PLU','MPART_SCA',2,'br','partner',0,300,'SCA_PLU','scanntech_entries','Envio de cadastro Scanntech','Cadastro',NULL,NULL,'partner',0,0),
            ('SCA_TPRO','MPART_SCA',2,'br','partner',0,200,'SCA_TPRO','scanntech_promo_item','Relatorio de Transmissão Resumo Promoções','Resumo Promoções',NULL,NULL,'partner',0,0),
            ('SCA_TRAN','MPART_SCA',2,'br','partner',0,100,'SCA_TRAN','scanntech_sale','Relatorio de Transmissão Scanntech','Transmissão',NULL,NULL,'partner',0,0),
            ('status',NULL,0,'br','main',0,89,'STATUS','index.php?mode=status','Administração do sistema e do servidor','Adm','glyphicon glyphicon-cog',NULL,NULL,1,0),
            ('STC_BATCH','stock',1,'br','stock',0,1410,'STC_BATCH','stock_batch','Estoque por Lote','Estoque por Lote',NULL,NULL,'stock',0,0),
            ('STC_CFOPTR','stock',1,'br','stock',0,55,'STC_CFOPTR','stock_cfop','CFOP de/para - Importação DOC_e','CFOP',NULL,NULL,'stock',0,0),
            ('STC_INVENT','stock',1,'br','stock',0,60,'STC_INVENT','stock_inventory','Controle de operações de inventário','Inventário',NULL,NULL,'stock',0,0),
            ('STC_INVOIC','stock',1,'br','stock',0,30,'STC_INVOIC','stock_invoice','Emissão de notas fiscais conjugadas','Nota Conjugada',NULL,NULL,'stock',0,0),
            ('STC_M1','stock',1,'br','stock',0,46,'AUTH','#','Abre ou fecha o menu','Menu',NULL,'this','stock',2,0),
            ('STC_M1_I1','STC_M1',2,'br','stock',0,47,'AUTH','http://xxxxx','Vai para xxxxx','xxxxx',NULL,NULL,'stock',0,0),
            ('STC_PRODOR','stock',1,'br','stock',0,1110,'STC_PRODOR','stock_production_order','Ordem de Produção','Ordem de Produção',NULL,NULL,'stock',0,0),
            ('STC_RECEIV','stock',1,'br','stock',0,20,'STC_RECEIV','stock_receiving','Digitação de notas fiscais de entrada e saída','Entrada de Notas',NULL,NULL,'stock',0,0),
            ('STC_RECIPE','stock',1,'br','stock',0,1100,'STC_RECIPE','stock_recipe','Receitas','Receitas',NULL,NULL,'stock',0,0),
            ('STC_REFUND','stock',1,'br','stock',0,1610,'STC_REFUND','stock_refund_entry','Lan?amento de Reembolso','Lan?amento de Reembolso (sem cupom)',NULL,NULL,'stock',0,1),
            ('STC_REQUES','stock',1,'br','stock',0,40,'STC_REQUES','stock_request','Digitação de requisições de mercadorias','Requisição',NULL,NULL,'stock',0,0),
            ('STC_RETURN','stock',1,'br','stock',0,1210,'STC_RECIPE','stock_return','Lançamento de Devoluções','Devolução',NULL,NULL,'stock',0,0),
            ('STC_TICKET','stock',1,'br','stock',0,10,'STC_TICKET','stock_ticket','Consulta de Notas','Consulta de Notas',NULL,NULL,'stock',0,0),
            ('STC_TRADE','stock',1,'br','stock',0,1510,'STC_TRADE','stock_trade','Lan?amento de Trocas','Troca (sem cupom)',NULL,NULL,'stock',0,1),
            ('STC_TYPE','stock',1,'br','stock',0,50,'STC_TYPE','stock_type','Manutenção da tabela de tipos de notas fiscais','Tipos de Notas',NULL,NULL,'stock',0,0),
            ('STC_VCHDSP','STC_VOUCHE',2,'br','stock',0,100,'STC_VCHDSP','stock_voucher','Voucher - Consulta','Disponíveis',NULL,NULL,'stock',0,0),
            ('STC_VCHUSD','STC_VOUCHE',2,'br','stock',0,200,'STC_VCHUSD','stock_voucher_used','Vouchers Resgatados','Resgatados',NULL,NULL,'stock',0,0),
            ('STC_VOUCHE','stock',1,'','stock',0,1310,'STC_VOUCHE','#','Vouchers','Vouchers',NULL,'this','stock',2,1),
            ('stock',NULL,0,'br','main',0,11,'STOCK','index.php?mode=stock','Controle de Estoque','Estoque','glyphicon glyphicon-tasks',NULL,NULL,1,0),
            ('store',NULL,0,'br','main',0,65,'STORE','index.php?mode=store','Controle de Lojas','Lojas','glyphicon glyphicon-home',NULL,NULL,1,0),
            ('STO_ACC','store',1,'br','store',0,120,'STO_ACC','store_accountant','Contabilidade','Contabilidade',NULL,NULL,'store',0,0),
            ('STO_CRRNC',NULL,1,'br','store',0,181,'STO_CRRNC','store_currency','Cotação','Cotação',NULL,NULL,'store',0,0),
            ('STO_DATA','store',1,'br','store',0,80,'STO_DATA','store_data','Variáveis por Loja','Variáveis por Loja',NULL,NULL,'store',0,0),
            ('STO_ECF','store',1,'br','store',0,40,'STO_ECF','store_ecf','Manutenção de ECF','ECF',NULL,NULL,'store',0,0),
            ('STO_ECFMDL','store',1,'br','store',0,2200,'STO_ECFMDL','store_ecf_model','Modelos de ECF','Modelos de ECF',NULL,NULL,'store',0,0),
            ('STO_ECFMKR','store',1,'br','store',0,2100,'STO_ECFMKR','store_ecf_maker','Fabricantes de ECF','Fabricantes de ECF',NULL,NULL,'store',0,0),
            ('STO_FILE','store',1,'br','store',0,20,'STO_FILE','store_file','Manutenção de Lojas','Lojas',NULL,NULL,'store',0,0),
            ('STO_FISCAL','store',1,'br','store',0,50,'STO_FISCAL','store_fiscal','Mapa Resumo ECF','Mapa Resumo',NULL,NULL,'store',0,0),
            ('STO_GROSTO','store',1,'br','store',0,370,'STO_GROSTO','store_group_list','Grupo de Lojas','Grupo de Lojas',NULL,NULL,'store',0,0),
            ('STO_GROUP','store',1,'br','store',0,350,'STO_GROUP','store_group_store','Grupos','Grupos',NULL,NULL,'store',0,0),
            ('STO_ITFPRM','store',1,'br','store',0,321,'STO_ITFPRM','store_interface_prm','Parâmetros de Interface','Parâmetros de Interface',NULL,NULL,'store',0,0),
            ('STO_LYTDPT','store',1,'br','store',0,2400,'STO_LYTDPT','store_layout_department','Layout por Departamentos','Layout por Departamentos',NULL,NULL,'store',0,0),
            ('STO_OPRSCH','store',1,'br','store',0,292,'STO_OPRSCH','store_opinion_research','Pesquisa de Opiniões','Pesquisa de Opiniões',NULL,NULL,'store',0,0),
            ('STO_PARAM','store',1,'br','store',0,70,'STO_PARAM','store_param','Parâmetros de Servidor por Loja','Parâmetros de Servidor',NULL,NULL,'store',0,0),
            ('STO_POS','store',1,'br','store',0,30,'STO_POS','store_pos','Manutenção de PDV','PDV',NULL,NULL,'store',0,0),
            ('STO_POSTYP','store',1,'br','store',0,2300,'STO_POSTYP','store_pos_types','Tipos de PDVs','Tipos de PDVs',NULL,NULL,'store',0,0),
            ('STO_PRM','store',1,'br','store',0,60,'STO_PRM','store_prm','Configuração de PDV\'s (global, loja, terminal)','Parâmetros de PDV',NULL,NULL,'store',0,0),
            ('STO_SAT','store',1,'br','store',0,45,'STO_SAT','store_sat','Manutenção de SAT','SAT',NULL,NULL,'store',0,0),
            ('STO_SATMDL','store',1,'br','store',0,2250,'STO_SATMDL','store_sat_model','Modelos de SAT','Modelos de SAT',NULL,NULL,'store',0,0),
            ('STO_SEND','store',1,'br','store',0,100,'STO_SEND','store_send_routes','Rotas/Nomes para exportação','Rotas/Nomes',NULL,NULL,'store',0,0),
            ('STO_TAX','store',1,'br','store',0,235,'STO_TAX','store_tax','Tributações por loja','Tributações por loja',NULL,NULL,'store',0,0),
            ('STO_TRIBUT','store',1,'br','store',0,2500,'STO_TRIBUT','store_tributo','Impostos do Mapa Resumo','Impostos',NULL,NULL,'store',0,0),
            ('STS_CHKSYS','status',1,'br','status',0,400,'STS_MENUT','status_checking_system','Checagens de indicadores do sistema','Checagem do sistema',NULL,NULL,'status',0,1),
            ('STS_CRYTY','status',1,'br','status',0,900,'STS_CRYTY','status_crypt_security','Cadastro de Acesso ao Banco','Cadastro de Acesso ao Banco',NULL,NULL,'status',0,0),
            ('STS_INDEX','status',1,'br','status',0,125,'STS_INDEX','status_index','Indices Complementares Opcionais','Indices',NULL,NULL,'status',0,0),
            ('STS_LIC','status',1,'br','status',0,90,'STS_LIC','status_lic','Informações da autorização de uso','Autorização',NULL,NULL,'status',0,0),
            ('STS_LOG','status',1,'br','status',0,70,'STS_LOG','status_log','Registro de transações executadas via Moderator','Log',NULL,NULL,'status',0,0),
            ('STS_MENU','status',1,'br','status',0,25,'STS_MENU','status_menu_systemt','Manutenção de Menu','Menu',NULL,NULL,'status',0,0),
            ('STS_MENUT','status',1,'br','status',0,200,'STS_MENU','status_menu_systemt','Manutenção dos Menus do Sistema','Menu Interativo',NULL,NULL,'status',0,0),
            ('STS_MNUTB','status',1,'','status',0,300,'STS_MENU','status_menu_systemt','Operações Batch no Menu do Sistema','Menu Batch',NULL,NULL,'status',0,0),
            ('STS_MSG','status',1,'br','status',0,80,'STS_MSG','status_msg','Mensagens enviadas pelo Emporium','Mensagens',NULL,NULL,'status',0,0),
            ('STS_MYSQL','status',1,'br','status',0,20,'STS_MYSQL','status_mysql','Status e variáveis do MySql','MySql',NULL,NULL,'status',0,0),
            ('STS_NOT','status',1,'br','status',0,75,'STS_NOT','status_notification','Registro de operações que precisam de atenção','Notificações',NULL,NULL,'status',0,0),
            ('STS_NOTSKU','status',1,'br','status',0,77,'STS_NOTSKU','status_not_sku','Registro de operações que precisam de atenção','Notificações Itens',NULL,NULL,'status',0,0),
            ('STS_PARAM','status',1,'br','status',0,60,'STS_PARAM','status_param','Parâmetros Globais','Globais',NULL,NULL,'status',0,0),
            ('STS_PHP','status',1,'br','status',0,10,'STS_PHP','status_php','Parâmetros e dados do PHP','PHP',NULL,NULL,'status',0,0),
            ('STS_QUERY','xstatus',1,'br','xstatus',0,200,'STS_SRV','status_query','Geração de query','Query',NULL,NULL,'xstatus',0,0),
            ('STS_REPAIR','status',1,'br','status',0,30,'STS_REPAIR','status_repair','Recuperação de tabelas','Recuperação',NULL,NULL,'status',0,0),
            ('STS_RMK','status',1,'br','status',0,750,'STS_RMK','status_remark','Ajuste de ticket','Ajuste de Ticket',NULL,NULL,'status',0,0),
            ('STS_SEND','status',1,'br','status',0,89,'STS_SEND','status_send','Configuração de envio','Configuração de envio',NULL,NULL,'status',0,0),
            ('STS_SETUP','status',1,'br','status',0,65,'STS_SETUP','status_setup','Configuração Do Sistema','Configuração Do Sistema',NULL,NULL,'status',0,0),
            ('STS_SRV','status',1,'br','status',0,88,'STS_SRV','status_srv','Informações do servidor','Servidor',NULL,NULL,'status',0,0),
            ('STS_SSURVEY','status',1,'br','status',0,825,'STS_SSURVE','status_satisfaction_survey','Pesquisa de satisfação','Pesquisa de satisfação',NULL,NULL,'status',0,0),
            ('STS_SYSTEM','status',1,'br','status',0,5,'STS_SYSTEM','status_system','Status do Emporium','Emporium',NULL,NULL,'status',0,0),
            ('STS_TIME','status',1,'br','status',0,100,'STS_TIME','status_time','Análise de Horários dos Elementos do Sistema','Horas',NULL,NULL,'status',0,0),
            ('STS_UPD','status',1,'br','status',0,600,'STS_UPD','status_upd','Atualização do sistema','Setup',NULL,NULL,'status',0,0),
            ('STS_UPDALL','status',1,'br','status',0,500,'STS_CHKSYS','status_update_all_store','Atulizações de cargas','Atulizações de cargas',NULL,NULL,'status',0,0),
            ('STS_UPDATE','status',1,'br','status',0,50,'STS_UPDATE','status_update','Nível de atualização de dados por loja e PDV','Atualizações',NULL,NULL,'status',0,0),
            ('STS_VERDB','status',1,'br','status',0,62,'STS_VERDB','status_version','Historivo de Versões DB','Versões DB',NULL,NULL,'status',0,0),
            ('STS_VERS',NULL,1,'br','status',0,160,'STS_VERS','status_progv','Versões Emporium','Versões Emporium',NULL,NULL,NULL,NULL,NULL),
            ('TCKT_VRFY','MIE_OTHER',2,'br','impexp',0,300,'TCKT_VRFY','cmcd_status','CMCD status','CMCD status',NULL,NULL,'impexp',0,0),
            ('treasury',NULL,0,'br','main',0,13,'TREASURY','index.php?mode=treasury','Operações de Tesouraria: seleção de sangrias, transferências, etc.','Tesouraria','glyphicon glyphicon-usd',NULL,NULL,1,0),
            ('TRE_ACCUM','treasury',1,'br','treasury',0,35,'TRE_ACCUM','treasury_accum','Acompanhamento on line de movimentações','Movimentação',NULL,NULL,'treasury',0,0),
            ('TRE_ACQUIR','treasury',1,'br','treasury',0,250,'TRE_ACQUIR','treasury_acquirr','Instituições','Instituições',NULL,NULL,'treasury',0,0),
            ('TRE_AQCUIR','treasury',1,'br','treasury',0,300,'TRE_AQCUIR','treasury_acquirr','Instituições','Instituições',NULL,NULL,'treasury',0,0),
            ('TRE_BALAN','treasury',1,'br','treasury',0,36,'TRE_BALAN','treasury_balance','Movimentação de saldo','Saldo',NULL,NULL,'treasury',0,0),
            ('TRE_BANKIN','treasury',1,'br','treasury',0,10,'TRE_BANKIN','treasury_banking','Seleção e manutenção de sangrias','Sangrias',NULL,NULL,'treasury',0,0),
            ('TRE_CSTC','treasury',1,'br','treasury',0,952,'TRE_CSTC','treasury_cost_center','Centro de Custos','Centro de Custos',NULL,NULL,'treasury',0,0),
            ('TRE_DAYSUM','treasury',1,'br','treasury',0,30,'TRE_DAYSUM','treasury_daysumm','Geração de resumo diário','Resumo Diário',NULL,NULL,'treasury',0,0),
            ('TRE_LOAN','treasury',1,'br','treasury',0,852,'TRE_LOAN','treasury_loan','Fundo de Troco de Operador','Fundo de Troco',NULL,NULL,'treasury',0,0),
            ('TRE_LOCAL','treasury',1,'br','treasury',0,50,'TRE_LOCAL','treasury_location','Manutenção da tabela de localizações','Localizações',NULL,NULL,'treasury',0,0),
            ('TRE_MNTBKN','treasury',1,'br','treasury',0,1102,'TRE_MNTBKN','treasury_banking_pos','Monitoramento de Sangrias por PDV','Monitoramento de Sangrias por PDV',NULL,NULL,'treasury',0,0),
            ('TRE_OPER','treasury',1,'br','treasury',0,40,'TRE_OPER','treasury_oper','Boletim diário por operador','Operadores',NULL,NULL,'treasury',0,0),
            ('TRE_PAYB','treasury',1,'br','treasury',0,1052,'TRE_PAYB','treasury_payable','Contas a Pagar','Contas a Pagar',NULL,NULL,'treasury',0,0),
            ('TRE_PICKUP','treasury',1,'br','treasury',0,70,'TRE_PICKUP','treasury_pickup','Inclusão de Sangria','Sangria',NULL,NULL,'treasury',0,0),
            ('TRE_REASON','treasury',1,'br','treasury',0,38,'treasury_r','treasury_reason','Motivos','Motivos',NULL,NULL,'treasury',0,0),
            ('TRE_REPOR','treasury',1,'br','treasury',0,100,'TRE_REPOR','treasury_report','Relatório','Relatório',NULL,NULL,'treasury',0,0),
            ('TRE_RETURN','treasury',1,'br','treasury',0,200,'TRE_RETURN','treasury_return','Trocas','Controle de Trocas',NULL,NULL,'treasury',0,0),
            ('TRE_TICKET','treasury',1,'br','treasury',0,60,'TRE_TICKET','treasury_ticket','Inclusão, alteração e exclusão de cupons','Edição de Cupons',NULL,NULL,'treasury',0,0),
            ('TRE_TRANS','treasury',1,'br','treasury',0,37,'TRE_TRANS','treasury_transaction','Manutenção de tipos de transações','Tipos de Transações',NULL,NULL,'treasury',0,0),
            ('TRE_XFER','treasury',1,'br','treasury',0,20,'TRE_XFER','treasury_xfer','Operações de tranferência em lotes','Lotes',NULL,NULL,'treasury',0,0),
            ('webservice','x_main',0,'br','x_main',0,86,'STO_TESTE','index.php?mode=webservice','WebService','WebService','img/webservice.png',NULL,NULL,1,0),
            ('WEB_DIG','webservice',1,'br','webservice',0,3570,'WEB_DIG','webservice_digital','Arquivo Digital','Arquivo Digital',NULL,NULL,'webservice',0,0),
            ('WEB_ECFSTS','webservice',1,'br','webservice',0,3580,'WEB_ECFSTS','webservice_ecf_stsx','Status ECF','Status ECF',NULL,NULL,'webservice',0,0),
            ('WEB_ECFSTX','webservice',1,'br','webservice',0,3680,'WEB_ECFSTX','webservice_ecf_stsx','Resumo de status de ECFs','Resumo ECF',NULL,NULL,'webservice',0,0),
            ('WEB_NFPU','webservice',1,'br','webservice',0,3560,'WEB_NFPU','webservice_nfp_users','Usuários Nota Fiscal Paulista','Usuários NFP',NULL,NULL,'webservice',0,0),
            ('WEB_STATUS','webservice',1,'br','webservice',0,3550,'WEB_STATUS','webservice_status','Status de Transações','Status',NULL,NULL,'webservice',0,0),
            ('WEB_TKTNFP','webservice',1,'br','webservice',0,3565,'WEB_TKTNFP','webservice_ticket_nfp','Tickets NFP','Tickets NFP',NULL,NULL,'webservice',0,0),
            ('WEB_URL','webservice',1,'br','webservice',0,3780,'WEB_URL','webservice_nfp_url','URL Cidadania Fiscal','URL Cidadania Fiscal',NULL,NULL,'webservice',0,0),
            ('XMLW','status',1,'br','status',0,150,'XMLW','/moderator-cgi/xmlwizard?mode=view','Situação dos parâmetros','XML',NULL,NULL,'status',0,0),
            ('zonasul',NULL,0,'br','main',0,88,'ZONASUL','index.php?mode=zonasul','ZonaSul','ZonaSul','glyphicon glyphicon-heart',NULL,NULL,1,0),
            ('ZSA_RVSKIT','',1,'br','zonasul',0,500,'ZSA_RVSKIT','zonasul_reverse_kit','Vendas de kit reverso','Vendas de kit reverso',NULL,NULL,'zonasul',0,0),
            ('ZS_AMORTI','zonasul',1,'br','zonasul',0,50,'ZS_AMORTI','zs_amortizacao','Amortização','Amortização',NULL,NULL,'zonasul',0,0),
            ('ZS_CHGMED','zonasul',1,'br','zonasul',0,60,'ZS_CHGMED','zs_return','Troca de finalizadora','Troca de finalizadora',NULL,NULL,'zonasul',0,0),
            ('ZS_ESTAUC','zonasul',1,'br','zonasul',0,70,'ZS_ESTAUC','zs_report_parking','Relatorio estacionamento Aucon','Relatorio estacionamento Aucon',NULL,NULL,'zonasul',0,0),
            ('ZS_ESTWPS','zonasul',1,'br','zonasul',0,71,'ZS_ESTWPS','zs_report_parking_wps','Relatorio estacionamento WPS','Relatorio estacionamento WPS',NULL,NULL,'zonasul',0,0),
            ('ZS_EXTRA','zonasul',1,'br','zonasul',0,25,'ZS_EXTRA','zs_amount_extra_ticket','Transf. Mercadoria','Transf. Mercadoria',NULL,NULL,'zonasul',0,0),
            ('ZS_LINK','zonasul',1,'br','zonasul',0,80,'ZS_LINK','zs_report_parking_link','Relatorio estacionamento Link','Relatorio estacionamento Link',NULL,NULL,'zonasul',0,0)"
        );


    }

}
